# Generated by Django 4.0.10 on 2023-02-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccount_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='nama',
            new_name='name',
        ),
    ]
