# Generated by Django 4.0.10 on 2023-02-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
