# Generated by Django 4.0.10 on 2023-02-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
