# Generated by Django 4.0.10 on 2023-02-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='nama',
            new_name='name',
        ),
    ]
